language: python
dist: bionic
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "pypy3-7.1.1"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script:
  - python setup.py sdist bdist_wheel
