name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.0
      with:
        extra_arg: --all-files --show-diff-on-failure
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.2
    - name: Poetry install
      run: poetry install
    - name: Run pytest
      run: poetry run pytest
