name: Deploy to PyPI

on: push

jobs:
  deploy:
    if: |
      github.event_name == 'push' &&
      startsWith(github.event.ref, 'refs/tags')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pip and tox
      run: python -m pip install --upgrade pip tox
    - name: Build
      run: tox -e build
    - name: Upload to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
      run: tox -e upload
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
